apiVersion: v1
kind: Service
metadata:
  name: ciquickstart
  labels:
    app: ciquickstart
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: ciquickstart
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciquickstart
  labels:
    app: ciquickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciquickstart
  template:
    metadata:
      labels:
        app: ciquickstart
    spec:
      containers:
      - name: ciquickstart
        image: peterhack/ciquickstart:5
        ports:
        - containerPort: 8080
